#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

n=1

while [ "$n" -le 100 ]; do


  if ! (( n % 3 )) && ! (( n % 5 )); then
    echo "FizzBuzz"
  elif ! (( n % 3 )); then
    echo "Fizz"
  elif ! (( n % 5 )); then
    echo "Buzz"
  else
    echo "$n"
  fi
  
  ((n++))
done
